#!/bin/bash


dir=func
declare -a failed=()

mkdir -p $dir
for output in `ls src/outputs | sed 's/\.js$//g'`; do
  bin/image-html -o $output example.png $dir/$output.html
  $BAKE render --viewport 200x199 $dir/$output.html $dir/$output.png
  # FIXME: use return status once that is fixed
  status=`node_modules/.bin/imagediff -e example.png $dir/$output.png`
  if [ "$status" != true ]; then
    failed=("${failed[@]}" "$output")
  fi
done

if [ ${#failed} -ne 0 ]; then
  echo "Failures: ${failed[@]}" >&2
  exit 1
fi
