#!/bin/bash


exe=$1
dir=tmp/func-$2
declare -a failed=()

mkdir -p $dir
for format in `ls src/formats | sed 's/\.js$//g'`; do
  $exe --format $format example.png $dir/$task-$format.html
  $BAKE render --viewport 200x199 $dir/$task-$format.html $dir/$task-$format.png
  # FIXME: use return status once that is fixed
  status=`node_modules/.bin/imagediff -e example.png $dir/$task-$format.png`
  if [ "$status" != true ]; then
    failed=("${failed[@]}" "$format")
  fi
done

if [ ${#failed} -ne 0 ]; then
  echo "Failures: ${failed[@]}" >&2
  exit 1
fi
