#!/bin/bash


exe=$1
dir=tmp/func-$2
declare -a failed=()

mkdir -p $dir
for output in `ls src/outputs | sed 's/\.js$//g'`; do
  if [ "$output" = index ]; then
    continue
  fi

  $exe -o $output example.png $dir/$task-$output.html
  $BAKE render --viewport 200x199 $dir/$task-$output.html $dir/$task-$output.png
  # FIXME: use return status once that is fixed
  status=`node_modules/.bin/imagediff -e example.png $dir/$task-$output.png`
  if [ "$status" != true ]; then
    failed=("${failed[@]}" "$output")
  fi
done

if [ ${#failed} -ne 0 ]; then
  echo "Failures: ${failed[@]}" >&2
  exit 1
fi
