#!/bin/bash


tmpfile=`mktemp /tmp/XXXXXX.html`
echo $PWD/node_modules/mocha/mocha.js
echo "<html>
  <head>
    <meta charset='utf-8' />
  </head>
  <body>
    <div id='mocha'></div>
    <script src='$PWD/node_modules/mocha/mocha.js'></script>
    <script src='$PWD/node_modules/expect.js/expect.js'></script>
    <script>mocha.ui('bdd')</script>
    <script src='$PWD/test/tests.js'></script>
    <script>mochaPhantomJS.run();</script>
  </body>
</html>" >"$tmpfile"
node_modules/.bin/mocha-phantomjs "$tmpfile"
rm "$tmpfile"
