#!/bin/bash


mkdir -p dist
outfile=dist/image-html.js
minfile=dist/image-html.min.js


function var(){
  sed -e "/$1/!d" -e 's;.*: *"\(.*\)".*;\1;' package.json
}


node_modules/.bin/browserify index.js --outfile $outfile


echo "/*! `var title` v`var version` - `var homepage` */" >$minfile
node_modules/.bin/uglifyjs $outfile --compress --mangle >>$minfile
