#!/bin/bash


mkdir -p dist
outfile=dist/image-html.js
minfile=dist/image-html.min.js


function var(){
  sed -e "/$1/!d" -e 's;.*: *"\(.*\)".*;\1;' package.json
}

function banner(){
  echo "/*! `var title` v`var version` - `var homepage` */"
}


banner >$outfile
node_modules/.bin/browserify browser.js >>$outfile


banner >$minfile
node_modules/.bin/uglifyjs $outfile --compress --mangle >>$minfile
