#!/bin/bash


mkdir -p dist


function var(){
  sed -e "/$1/!d" -e 's;.*: *"\(.*\)".*;\1;' package.json
}

function banner(){
  echo "/*! `var title`$1 v`var version` - `var homepage` */"
}


outfile=dist/image-html.all.js
banner '.all' >$outfile
node_modules/.bin/browserify browser.all.js | node_modules/.bin/uglifyjs --mangle --compress warnings=false >>$outfile


outfile=dist/image-html.js
banner >$outfile
node_modules/.bin/browserify browser.js | node_modules/.bin/uglifyjs --mangle --compress warnings=false >>$outfile
